# Generated by Django 5.2.7 on 2026-03-18 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='bill',
            name='customer_name',
            field=models.CharField(default='Guest', max_length=200),
        ),
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(default='open', max_length=20),
        ),
    ]
