# Generated by Django 6.0.3 on 2026-03-20 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_bill_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=15, unique=True)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('waiter', 'Waiter'), ('chef', 'Chef'), ('cashier', 'Cashier')], max_length=20)),
                ('password', models.CharField(max_length=4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
