# Generated by Django 5.2.7 on 2026-03-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_bill_customer_bill_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('online', 'Online'), ('card', 'Card')], max_length=10, null=True),
        ),
    ]
