# Generated by Django 5.2.7 on 2026-03-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_bill_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('pending', 'Pending Payment'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='open', max_length=10),
        ),
    ]
