# Generated by Django 6.0.3 on 2026-03-20 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_bill_discount_amount'),
        ('billing', '0006_staff'),
    ]

    operations = [
    ]
