# Generated by Django 6.0.3 on 2026-03-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_merge_0006_bill_discount_amount_0006_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('captain', 'Captain'), ('cashier', 'Cashier')], max_length=20),
        ),
    ]
